"""
Create the unified `JuDDGES/juddges-pl` dataset on Hugging Face for the
NeurIPS 2026 E&D submission.

Strategy: rather than duplicating ~10s of GB of parquet, we publish a
README whose YAML frontmatter declares two configs (`pl-court` and
`pl-nsa`) whose `data_files` point to the explicit list of auto-converted
parquet files of the upstream JuDDGES/pl-court-raw-enriched and
JuDDGES/pl-nsa-enriched datasets via cross-repo `resolve/...` URLs.

Run:
    python publish_juddges_pl.py            # build README + create/update repo + validate
    python publish_juddges_pl.py --dry-run  # build README locally, do not upload
    python publish_juddges_pl.py --validate # validate loading only
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
import urllib.request
from pathlib import Path

REPO_ID = "JuDDGES/juddges-pl"
HERE = Path(__file__).parent

UPSTREAM = {
    "pl-court": "JuDDGES/pl-court-raw-enriched",
    "pl-nsa":   "JuDDGES/pl-nsa-enriched",
}


def list_upstream_parquet(hf_id: str) -> list[str]:
    """Enumerate the auto-converted parquet files for an upstream dataset."""
    api_url = f"https://huggingface.co/api/datasets/{hf_id}/tree/refs%2Fconvert%2Fparquet/default/train"
    with urllib.request.urlopen(api_url, timeout=60) as resp:
        items = json.loads(resp.read().decode("utf-8"))
    paths = sorted(
        x["path"]
        for x in items
        if x.get("type") == "file" and x.get("path", "").endswith(".parquet")
    )
    return [
        f"https://huggingface.co/datasets/{hf_id}/resolve/refs%2Fconvert%2Fparquet/{p}"
        for p in paths
    ]


BODY = textwrap.dedent(
    """\
    # JuDDGES-pl

    **JuDDGES-pl** is a unified Polish court judgment corpus for civil-law legal NLP,
    accompanying the NeurIPS 2026 Evaluations & Datasets Track submission
    *"JuDDGES-pl: Hundreds of Thousands of Structurally Enriched Polish Judgments
    from Common and Administrative Courts"*.

    The corpus combines two disjoint branches of the Polish judiciary into a single
    Hugging Face dataset with two configs:

    | Config | Source | Coverage | Rows |
    |---|---|---|---|
    | `pl-court` | [JuDDGES/pl-court-raw-enriched](https://huggingface.co/datasets/JuDDGES/pl-court-raw-enriched) | Common courts (Supreme Court, courts of appeal, regional and district courts) | 100K–1M |
    | `pl-nsa` | [JuDDGES/pl-nsa-enriched](https://huggingface.co/datasets/JuDDGES/pl-nsa-enriched) | Administrative courts (Supreme Administrative Court and lower) | 1M–10M |

    Each judgment includes:

    - **Verbatim source content** (text, signature, court name, judges, dates, statute references) preserved from the official Polish court publication portals.
    - **LLM-extracted analytical fields** generated by a uniform Google Gemini 2.5 Pro extraction pipeline: `factual_state`, `legal_state`, `extracted_summary`, `extracted_thesis`, `extracted_legal_bases`, `extracted_keywords`, `extracted_title`.

    ## ⚠️ Silver-label commitment

    The LLM-extracted fields are **silver labels**: produced by a single model under
    uniform prompting, **without per-document human validation at corpus scale**.

    - **Use them for:** descriptive analysis, model pretraining, weak supervision, retrieval indexing.
    - **Do not use them for:** benchmarking with held-out test sets, regulatory or
      individual legal decisions.
    - **Always cite the model version** (Google Gemini 2.5 Pro) when reporting
      analyses derived from these fields, since LLM behavior shifts across releases.

    A separate validated subset (`JuDDGES/pl-swiss-franc-loans`) provides gold
    annotations for tasks requiring high-fidelity labels.

    ## Loading

    ```python
    from datasets import load_dataset

    common = load_dataset("JuDDGES/juddges-pl", "pl-court", split="train", streaming=True)
    nsa    = load_dataset("JuDDGES/juddges-pl", "pl-nsa",   split="train", streaming=True)

    for row in common.take(3):
        print(row["court_name"], row["signature"], row["extracted_summary"][:120])
    ```

    ## Licensing

    - **Source judgments**: public-domain legal acts under Polish copyright law
      (Art. 4 pkt 2 of the Ustawa o prawie autorskim — *orzeczenia sądów* are
      *dokumenty urzędowe* and not subject to copyright).
    - **Enrichment layer** (LLM-extracted analytical fields, structured metadata,
      Croissant): released under **CC BY 4.0**.

    ## Privacy

    Source judgments are pseudonymized at the court level before publication
    (personal names of natural persons → initials/codes; PESEL, addresses,
    dates of birth redacted). Names of public officials, judges, and corporate
    parties are typically retained as legally permitted. We perform no
    additional de-anonymization. Users redistributing derivatives must comply
    with GDPR/RODO and must not attempt re-identification.

    ## Maintenance

    Maintained by the [JuDDGES organization](https://huggingface.co/JuDDGES) at
    Wrocław University of Science and Technology. Versioned via Hugging Face
    commits; dataset card updates announce material changes.

    ## Citation

    ```bibtex
    @inproceedings{juddges-pl-2026,
      title     = {JuDDGES-pl: Hundreds of Thousands of Structurally Enriched Polish Judgments from Common and Administrative Courts},
      author    = {Augustyniak, {\\L}ukasz and others},
      booktitle = {NeurIPS 2026 Evaluations and Datasets Track},
      year      = {2026}
    }
    ```

    ## Croissant metadata

    Croissant JSON-LD with full Responsible AI fields is released alongside the
    paper (NeurIPS 2026 supplementary material).
    """
)


def build_readme() -> str:
    yaml_lines: list[str] = []
    for cfg, upstream in UPSTREAM.items():
        print(f"  Listing parquet files for {upstream} ...")
        urls = list_upstream_parquet(upstream)
        print(f"    {cfg}: {len(urls)} files")
        yaml_lines.append(f"- config_name: {cfg}")
        yaml_lines.append(f"  data_files:")
        yaml_lines.append(f"  - split: train")
        yaml_lines.append(f"    path:")
        for u in urls:
            yaml_lines.append(f"    - \"{u}\"")
    configs_yaml = "\n".join(yaml_lines)

    frontmatter = (
        "---\n"
        "license: cc-by-4.0\n"
        "language:\n"
        "- pl\n"
        "pretty_name: \"JuDDGES-pl: Polish Court Judgment Corpus for Civil-Law Legal NLP\"\n"
        "tags:\n"
        "- legal\n"
        "- polish\n"
        "- civil-law\n"
        "- silver-labels\n"
        "- llm-extracted\n"
        "- judgments\n"
        "- JuDDGES\n"
        "size_categories:\n"
        "- 1M<n<10M\n"
        "task_categories:\n"
        "- text-generation\n"
        "- text-classification\n"
        "- summarization\n"
        "- feature-extraction\n"
        "configs:\n"
        f"{configs_yaml}\n"
        "---\n\n"
    )
    return frontmatter + BODY


def create_or_update(readme_text: str) -> None:
    from huggingface_hub import HfApi

    api = HfApi()
    api.create_repo(repo_id=REPO_ID, repo_type="dataset", exist_ok=True)
    print(f"Repo ensured: {REPO_ID}")

    readme_path = HERE / "_juddges_pl_README.md"
    readme_path.write_text(readme_text, encoding="utf-8")
    print(f"Wrote local README ({readme_path.stat().st_size:,} bytes)")

    api.upload_file(
        path_or_fileobj=str(readme_path),
        path_in_repo="README.md",
        repo_id=REPO_ID,
        repo_type="dataset",
        commit_message="Add JuDDGES-pl dataset card with cross-repo configs (NeurIPS 2026 E&D)",
    )
    print(f"Uploaded README to https://huggingface.co/datasets/{REPO_ID}")


def validate() -> None:
    from datasets import load_dataset

    for cfg in UPSTREAM:
        print(f"\nLoading {REPO_ID} :: {cfg} (streaming) ...")
        try:
            ds = load_dataset(REPO_ID, cfg, split="train", streaming=True)
            row = next(iter(ds.take(1)))
            keys = list(row.keys())[:8]
            print(f"  OK — first-row keys (first 8 of {len(row)}): {keys}")
        except Exception as exc:  # noqa: BLE001
            print(f"  FAILED: {type(exc).__name__}: {exc}")
            print("  ↳ Cross-repo data_files URLs may not be supported here.")
            print("    Fallback: use a loading script (juddges-pl.py) or copy parquet files.")
            sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true", help="build README locally, do not upload")
    parser.add_argument("--validate", action="store_true", help="skip create/upload; only validate loading")
    args = parser.parse_args()

    if args.validate:
        validate()
        return

    print("Building README ...")
    readme_text = build_readme()
    if args.dry_run:
        out = HERE / "_juddges_pl_README.md"
        out.write_text(readme_text, encoding="utf-8")
        print(f"Dry run — wrote local README to {out}")
        return

    create_or_update(readme_text)
    print()
    validate()


if __name__ == "__main__":
    main()
