repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        name: No commits to master
      - id: end-of-file-fixer
        name: End-of-file fixer
      - name: mixed-line-ending
        id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: check-toml
        name: Check toml
      - id: check-yaml
        name: Check yaml
        args: [--allow-multiple-documents]


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        name: Ruff Linter
        args: [--fix, --exit-non-zero-on-fix, juddges, scripts, dashboards, tests]
      - id: ruff-format
        name: Ruff Formatter
        args: [juddges, scripts, dashboards, tests]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.3
    hooks:
      - id: gitleaks
        language_version: 1.23.6 # due to: https://github.com/gitleaks/gitleaks/issues/1751

exclude: 'data/|dvc.lock'
