name: juddges

services:
  web:
    build: .
    command: streamlit run /app/juddges/dashboards/app.py
    volumes:
      - ./:/app
      - ~/.cache:/root/.cache
      # - L:\docker-configs\zsh\smartass_zsh_history:/root/.zsh_history
    tty: true
    shm_size: "2gb"
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA. Required to avoid "CUDA version: N/A"
                - video # NVDEC/NVENC. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need it
    networks:
      - juddges-network

  auth:
    restart: always
    build: ./nginx
    ports:
      - ${DASHBOARD_PORT}:8080
    volumes:
      - ./nginx/auth.conf:/etc/nginx/conf.d/auth.conf:ro
    networks:
      - juddges-network
    environment:
      - USER=${NGINX_USER}
      - PASS=${NGINX_PASSWORD}

  postgres:
    image: postgres:latest
    container_name: postgres-juddges
    ports:
      - 3456:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-juddges-db:/var/lib/postgresql/data
    restart: always
    networks:
      - juddges-network

networks:
  juddges-network:
    driver: bridge

volumes:
  postgres-juddges-db:
