stages:
  build_fine_tuning_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/sft/build_fine_tuning_dataset.py
      --dataset-dir data/datasets/pl/raw
      --repo-id JuDDGES/pl-court-instruct
    deps:
      - data/datasets/pl/raw
      - scripts/sft/build_fine_tuning_dataset.py
    desc: "Build synthetic instriction dataset (set NUM_JOBS envar)"

  fine_tune_sft:
    foreach:
      - Mistral-7B-Instruct-v0.2
      - Meta-Llama-3-8B-Instruct
    do:
      cmd: >-
        PYTHONPATH=. python scripts/sft/fine_tune_llm.py model=${item}
      deps:
        - scripts/sft/fine_tune_llm.py
      outs:
        - data/experiments/fine-tune/${item}/pl-court-instruct

  evaluate_zero_shot:
    matrix:
      config:
        - llm: "meta-llama/Meta-Llama-3-8B-Instruct"
          fname: "meta_llama_3_8B_instruct"
        # - llm: "mistralai/Mistral-7B-Instruct-v0.2"
        #   fname: "mistral_7B_instruct_v0.2"
    cmd: >-
      PYTHONPATH=. python scripts/sft/evaluate_zero_shot.py
      --llm ${item.config.llm}
      --output-file data/results/pl_court_instruct/zero_shot/results_${item.config.fname}.json
      --metrics-file data/results/pl_court_instruct/zero_shot/metrics_${item.config.fname}.json
    deps:
      - scripts/sft/evaluate_zero_shot.py
    outs:
      - data/results/pl_court_instruct/zero_shot/results_${item.config.fname}.json
    metrics:
      - data/results/pl_court_instruct/zero_shot/metrics_${item.config.fname}.json:
          cache: false