stages:
  build_fine_tuning_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/sft/build_fine_tuning_dataset.py
      --dataset-dir data/datasets/pl/raw
      --repo-id JuDDGES/pl-court-instruct
    deps:
      - data/datasets/pl/raw
      - scripts/sft/build_fine_tuning_dataset.py
    desc: "Build synthetic instriction dataset (set NUM_JOBS envar)"

  fine_tune_sft:
    foreach:
      - Mistral-7B-Instruct-v0.2
      - Meta-Llama-3-8B-Instruct
    do:
      cmd: >-
        PYTHONPATH=. python scripts/sft/fine_tune_llm.py model=${item}
      deps:
        - scripts/sft/fine_tune_llm.py
      outs:
        - data/experiments/fine-tune/${item}/pl-court-instruct

  predict:
    matrix:
      config:
        - Mistral-7B-Instruct-v0.2
        - Meta-Llama-3-8B-Instruct
        - Mistral-7B-Instruct-v0.2-fine-tuned
    cmd: >-
      PYTHONPATH=. python scripts/sft/predict.py model=${item.config}
    deps:
      - scripts/sft/predict.py
    outs:
      - data/experiments/predict/pl-court-instruct/${item.config}
