stages:
  build_fine_tuning_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/sft/build_fine_tuning_dataset.py
      --dataset-dir data/datasets/pl/raw
      --repo-id JuDDGES/pl-court-instruct
    deps:
      - data/datasets/pl/raw
      - scripts/sft/build_fine_tuning_dataset.py
    desc: "Build instriction dataset (set NUM_JOBS envar) with labels extracted from API/text"

  embed:
    matrix:
      model:
        - mmlw-roberta-large
    cmd: >-
      PYTHONPATH=. python scripts/embed/embed_text.py embedding_model=${item.model}
    deps:
      - scripts/embed/embed_text.py
      - configs/embedding.yaml
      - configs/embedding_model/${item.model}.yaml
      - data/datasets/pl/raw
    outs:
      - data/embeddings/pl-court-raw/${item.model}/all_embeddings

  aggregate_embeddings:
    matrix:
      model:
        - mmlw-roberta-large
    cmd: >-
      PYTHONPATH=. python scripts/embed/aggregate_embeddings.py 
      --embeddings-dir data/embeddings/pl-court-raw/${item.model}/all_embeddings
    deps:
      - scripts/embed/aggregate_embeddings.py
      - data/embeddings/pl-court-raw/${item.model}/all_embeddings
    outs:
      - data/embeddings/pl-court-raw/${item.model}/agg_embeddings.pt

  
  generate_graph_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/dataset/generate_graph_dataset.py
      --dataset-dir data/datasets/pl/raw 
      --embeddings-root-dir data/embeddings/pl-court-raw/mmlw-roberta-large/
      --target-dir data/datasets/pl/graph
    deps:
      - scripts/dataset/generate_graph_dataset.py
      - juddges/data/pl_court_graph.py
      - data/datasets/pl/raw 
      - data/embeddings/pl-court-raw/mmlw-roberta-large/agg_embeddings.pt
      - data/embeddings/pl-court-raw/mmlw-roberta-large/all_embeddings/config.yaml
    outs:
      - data/datasets/pl/graph/data
      - data/datasets/pl/graph/metadata.yaml

  graph_dataset_readme:
    cmd: >-
      jupyter nbconvert 
      --no-input 
      --to markdown 
      --execute nbs/Data/03_Graph_Dataset_Description.ipynb
      --output-dir data/datasets/pl/graph
      --output README
    deps:
      - nbs/Data/03_Graph_Dataset_Description.ipynb
      - data/datasets/pl/graph/data
    outs:
      - data/datasets/pl/graph/README.md
      - data/datasets/pl/graph/README_files

  sft:
    matrix:
      model:
        - Mistral-7B-Instruct-v0.2
    cmd: >-
      PYTHONPATH=. python scripts/sft/fine_tune_llm.py model=${item.model}
    deps:
      - scripts/sft/fine_tune_llm.py
      - configs/fine_tuning.yaml
      - configs/model/${item.model}.yaml
    outs:
      - data/experiments/fine-tune/${item.model}/pl-court-instruct
    frozen: true

  sft_unsloth:
    matrix:
      model:
        - Unsloth-Llama-3-8B-Instruct
        - Unsloth-Mistral-7B-Instruct-v0.3
    cmd: >-
      PYTHONPATH=. python scripts/sft/fine_tune_unsloth.py model=${item.model}
    deps:
      - scripts/sft/fine_tune_unsloth.py
      - configs/fine_tuning.yaml 
      - configs/model/${item.model}.yaml
    outs:
      - data/experiments/fine-tune/${item.model}/pl-court-instruct

  predict:
    matrix:
      model:
        - Meta-Llama-3-8B-Instruct
        - Mistral-7B-Instruct-v0.2
        - Mistral-7B-Instruct-v0.2-fine-tuned
        - Bielik-7B-Instruct-v0.1
        - Unsloth-Llama-3-8B-Instruct
        - Unsloth-Llama-3-8B-Instruct-fine-tuned
        - Unsloth-Mistral-7B-Instruct-v0.3
        - Unsloth-Mistral-7B-Instruct-v0.3-fine-tuned
    cmd: >-
      PYTHONPATH=. python scripts/sft/predict.py model=${item.model}
    deps:
      - scripts/sft/predict.py
      - configs/predict.yaml
      - configs/model/${item.model}.yaml
    outs:
      - data/experiments/predict/pl-court-instruct/outputs_${item.model}.json

  evaluate:
    matrix:
      model:
        - Unsloth-Llama-3-8B-Instruct
        - Unsloth-Llama-3-8B-Instruct-fine-tuned
        - Unsloth-Mistral-7B-Instruct-v0.3
        - Unsloth-Mistral-7B-Instruct-v0.3-fine-tuned
        - Bielik-7B-Instruct-v0.1
    cmd: >-
      PYTHONPATH=. python scripts/sft/evaluate.py 
      --output-file data/experiments/predict/pl-court-instruct/outputs_${item.model}.json
    deps:
      - scripts/sft/evaluate.py
      - data/experiments/predict/pl-court-instruct/outputs_${item.model}.json
    metrics:
      - data/experiments/predict/pl-court-instruct/metrics_${item.model}.json:
          cache: false

  summarize_metrics:
    matrix:
      dir:
        - data/experiments/predict/pl-court-instruct
    cmd: >-
      PYTHONPATH=. python scripts/sft/summarize_metrics.py 
      --root-dir ${item.dir}
    deps:
      - scripts/sft/summarize_metrics.py
    metrics:
      - ${item.dir}/metrics_summary.md:
          cache: false
