stages:
  build_fine_tuning_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/sft/build_fine_tuning_dataset.py
      --dataset-dir data/datasets/pl/raw
      --repo-id JuDDGES/pl-court-instruct
    deps:
      - data/datasets/pl/raw
      - scripts/sft/build_fine_tuning_dataset.py
    desc: "Build synthetic instriction dataset (set NUM_JOBS envar)"

  fine_tune_sft:
    foreach:
      - Mistral-7B-Instruct-v0.2
      - Meta-Llama-3-8B-Instruct
    do:
      cmd: >-
        PYTHONPATH=. python scripts/sft/fine_tune_llm.py model=${item}
      deps:
        - scripts/sft/fine_tune_llm.py
      outs:
        - data/experiments/fine-tune/${item}/pl-court-instruct

  evaluate_zero_shot:
    cmd: >-
      PYTHONPATH=. python scripts/sft/evaluate_zero_shot.py
      --output-file data/results/pl/zero_shot/results_llama_3_8B.json
      --metrics-file data/results/pl/zero_shot/metrics_llama_3_8B.json
    deps:
      - scripts/sft/evaluate_zero_shot.py
    outs:
      - data/results/pl/zero_shot/results_llama_3_8B.json
    metrics:
      - data/results/pl/zero_shot/metrics_llama_3_8B.json:
          cache: false