vars:
  - seeds: [42, 7312, 997]

stages:
  raw_dataset_readme:
    cmd: >-
      jupyter nbconvert
      --no-input
      --to markdown
      --execute 'nbs/Dataset Cards/01_Dataset_Description_Raw.ipynb'
      --output-dir data/datasets/pl/pl-court-raw
      --output README
    deps:
      - nbs/Dataset Cards/01_Dataset_Description_Raw.ipynb
      - data/datasets/pl/pl-court-raw/data/
    outs:
      - data/datasets/pl/pl-court-raw/README.md
      - data/datasets/pl/pl-court-raw/README_files/

  embed:
    matrix:
      model:
        - mmlw-roberta-large
    cmd: >-
      PYTHONPATH=. python scripts/embed/embed_text.py embedding_model=${item.model}
    deps:
      - scripts/embed/embed_text.py
      - configs/embedding.yaml
      - configs/embedding_model/${item.model}.yaml
      - data/datasets/pl/raw
    outs:
      - data/embeddings/pl-court-raw/${item.model}/all_embeddings

  aggregate_embeddings:
    matrix:
      model:
        - mmlw-roberta-large
    cmd: >-
      PYTHONPATH=. python scripts/embed/aggregate_embeddings.py
      --embeddings-dir data/embeddings/pl-court-raw/${item.model}/all_embeddings
    deps:
      - scripts/embed/aggregate_embeddings.py
      - data/embeddings/pl-court-raw/${item.model}/all_embeddings
    outs:
      - data/embeddings/pl-court-raw/${item.model}/agg_embeddings.pt

  build_graph_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/dataset/build_graph_dataset.py
      --dataset-dir data/datasets/pl/raw
      --embeddings-root-dir data/embeddings/pl-court-raw/mmlw-roberta-large/
      --target-dir data/datasets/pl/graph
    deps:
      - scripts/dataset/build_graph_dataset.py
      - juddges/data/pl_court_graph.py
      - data/datasets/pl/raw
      - data/embeddings/pl-court-raw/mmlw-roberta-large/agg_embeddings.pt
      - data/embeddings/pl-court-raw/mmlw-roberta-large/all_embeddings/config.yaml
    outs:
      - data/datasets/pl/graph/data
      - data/datasets/pl/graph/metadata.yaml

  build_swiss_franc_loans_instruct_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/dataset/build_swiss_franc_loans_instruct_dataset.py
      --dataset-source-path data/datasets/pl/swiss_franc_loans_source/
      --output-dir data/datasets/pl/swiss_franc_loans
      --tokenizer-name meta-llama/Llama-3.1-8B-Instruct
      --schema-path configs/ie_schema/swiss_franc_loans.yaml
      --threshold-tokens 64_000
    deps:
      - scripts/dataset/build_swiss_franc_loans_instruct_dataset.py
      - configs/ie_schema/swiss_franc_loans.yaml
      - data/datasets/pl/swiss_franc_loans_source/
    outs:
      - data/datasets/pl/swiss_franc_loans/test.json
      - data/datasets/pl/swiss_franc_loans/annotated.json
      - data/datasets/pl/swiss_franc_loans/dataset_info.json
      # - data/datasets/pl/swiss_franc_loans/train.json

  build_en_appealcourt_coded_dataset:
    cmd: >-
      PYTHONPATH=. python scripts/dataset/build_en_appealcourt_coded_dataset.py
      --target-dir data/datasets/en/en_appealcourt_coded
      --schema-file configs/ie_schema/en_appealcourt.yaml
    deps:
      - scripts/dataset/build_en_appealcourt_coded_dataset.py
      - configs/ie_schema/en_appealcourt.yaml
    outs:
      - data/datasets/en/en_appealcourt_coded/annotated.json
      - data/datasets/en/en_appealcourt_coded/dataset_info.json

  ### ---------------------------- Fine-tuning ---------------------------- ###
  sft:
    matrix: &sft_models
      llm_dataset:
        - dataset: pl_court_swiss_franc_loans
          llm: llama_3.1_8b_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: llama_3.2_3b_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: mistral_nemo_instruct_2407
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: pllum_12b_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: bielik_11b_v23_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
    cmd: >-
      PYTHONPATH=. python scripts/sft/fine_tune_deepspeed.py
      dataset=${item.llm_dataset.dataset}
      llm=${item.llm_dataset.llm}
      prompt=${item.llm_dataset.prompt}
      ie_schema=${item.llm_dataset.ie_schema}
    deps:
      - scripts/sft/fine_tune_deepspeed.py
      - configs/peft_fine_tuning.yaml
      - configs/llm/${item.llm_dataset.llm}.yaml
    outs:
      - data/experiments/peft-fine-tune/${item.llm_dataset.llm}/${item.llm_dataset.dataset}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/

  ### ---------------------------- Evaluate with human annotations ---------------------------- ###
  convert_splits_to_predcictions:
    cmd: >-
      PYTHONPATH=. python scripts/dataset/convert_pl_swiss_franc_loans_splits_to_eval_data.py
      --dataset-name-or-path data/datasets/pl/swiss_franc_loans
      --output-dir data/experiments/predict/raw/pl_court_swiss_franc_loans/test/gpt_4.1/
    deps:
      - scripts/dataset/convert_pl_swiss_franc_loans_splits_to_eval_data.py
      - data/datasets/pl/swiss_franc_loans
    outs:
      - data/experiments/predict/raw/pl_court_swiss_franc_loans/test/gpt_4.1/predictions.json

  ### ---------------------------- Prediction ---------------------------- ###
  predict_swiss_franc_loans_raw_vllm:
    matrix:
      llm_dataset:
        - dataset: pl_court_swiss_franc_loans
          llm: llama_3.1_8b_instruct
          prompt: info_extraction_annotated_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: llama_3.2_3b_instruct
          prompt: info_extraction_annotated_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: mistral_nemo_instruct_2407
          prompt: info_extraction_annotated_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: pllum_12b_instruct
          prompt: info_extraction_annotated_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: bielik_11b_v23_instruct
          prompt: info_extraction_annotated_json
          ie_schema: swiss_franc_loans
        ###
        - dataset: en_appealcourt_coded
          llm: llama_3.1_8b_instruct
          prompt: info_extraction_json
          ie_schema: en_appealcourt
        - dataset: en_appealcourt_coded
          llm: llama_3.2_3b_instruct
          prompt: info_extraction_json
          ie_schema: en_appealcourt
        - dataset: en_appealcourt_coded
          llm: mistral_nemo_instruct_2407
          prompt: info_extraction_json
          ie_schema: en_appealcourt
      seed: ${seeds}
      split:
        - annotated
    cmd: >-
      PYTHONPATH=. python scripts/sft/predict_vllm.py
      dataset=${item.llm_dataset.dataset}
      llm=${item.llm_dataset.llm}
      prompt=${item.llm_dataset.prompt}
      ie_schema=${item.llm_dataset.ie_schema}
      random_seed=${item.seed}
      split=${item.split}
      output_dir=data/experiments/predict/raw_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}
    deps:
      - scripts/sft/predict_vllm.py
      - configs/predict.yaml
      - configs/llm/${item.llm_dataset.llm}.yaml
      - configs/prompt/${item.llm_dataset.prompt}.yaml
      - configs/ie_schema/${item.llm_dataset.ie_schema}.yaml
    outs:
      - data/experiments/predict/raw_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.json
      - data/experiments/predict/raw_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/dataset.json
      - data/experiments/predict/raw_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/config.yaml

  predict_swiss_franc_loans_on_fine_tuned_vllm:
    matrix:
      <<: *sft_models
      seed: ${seeds}
      split:
        - annotated
    cmd: >-
      PYTHONPATH=. python scripts/sft/predict_vllm.py
      dataset=${item.llm_dataset.dataset}
      llm=${item.llm_dataset.llm}
      prompt=${item.llm_dataset.prompt}
      ie_schema=${item.llm_dataset.ie_schema}
      random_seed=${item.seed}
      split=${item.split}
      llm.adapter_path=data/experiments/peft-fine-tune/${item.llm_dataset.llm}/${item.llm_dataset.dataset}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/
      output_dir=data/experiments/predict/fine_tuned_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}
    deps:
      - scripts/sft/predict_vllm.py
      - configs/predict.yaml
      - configs/llm/${item.llm_dataset.llm}.yaml
      - configs/prompt/${item.llm_dataset.prompt}.yaml
      - configs/ie_schema/${item.llm_dataset.ie_schema}.yaml
      - data/experiments/peft-fine-tune/${item.llm_dataset.llm}/${item.llm_dataset.dataset}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/
    outs:
      - data/experiments/predict/fine_tuned_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.json
      - data/experiments/predict/fine_tuned_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/dataset.json
      - data/experiments/predict/fine_tuned_vllm/${item.llm_dataset.dataset}/${item.split}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/config.yaml


  ### ---------------------------- Evaluation ---------------------------- ###
  evaluate: # use with NUM_PROC
    matrix:
      <<: *sft_models
      seed: ${seeds}
      model_type:
        - raw
        - fine_tuned
      split:
        - annotated
    cmd: >-
      PYTHONPATH=. python scripts/sft/evaluate.py
      --output-file data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.jsonl
      --num-proc=-1
    deps:
      - scripts/sft/evaluate.py
      - data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.jsonl
    outs:
      - data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/metrics.json

  evaluate_llm_as_judge:
    matrix:
      llm_dataset:
        - dataset: pl_court_swiss_franc_loans
          llm: llama_3.2_3b_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
        - dataset: pl_court_swiss_franc_loans
          llm: bielik_11b_v23_instruct
          prompt: info_extraction_json
          ie_schema: swiss_franc_loans
      seed: ${seeds}
      model_type:
        - raw
        - fine_tuned
      judge_llm:
        - gpt-4.1-mini-2025-04-14
    cmd: >-
      PYTHONPATH=. python scripts/sft/llm_as_judge.py
      data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.jsonl
      configs/ie_schema/swiss_franc_loans.yaml
      --judge-model=${item.judge_llm}
    deps:
      - scripts/sft/llm_as_judge.py
      - configs/ie_schema/swiss_franc_loans.yaml
      - data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/predictions.jsonl
    outs:
      - data/experiments/predict/${item.model_type}/${item.llm_dataset.dataset}/${item.llm_dataset.llm}/${item.llm_dataset.prompt}/${item.llm_dataset.ie_schema}/seed_${item.seed}/llm_as_judge_${item.judge_llm}.json

  summarize_metrics:
    matrix:
      dir:
        - data/experiments/predict/raw/pl_court_swiss_franc_loans
        - data/experiments/predict/fine_tuned/pl_court_swiss_franc_loans
    cmd: >-
      PYTHONPATH=. python scripts/sft/summarize_metrics.py
      --root-dir ${item.dir}
    deps:
      - scripts/sft/summarize_metrics.py
    metrics:
      - ${item.dir}/metrics_ngram_summary.md:
          cache: false
      - ${item.dir}/metrics_judge_summary.md:
          cache: false
