[tool.ruff]
line-length = 100
extend-include = ["*.ipynb"]
exclude = ["_modidx.py"]

[tool.mypy]
python_version = "3.11"
strict = true
untyped_calls_exclude = ["pymongo"]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = ["pyarrow.*", "datasets.*", "sentence_transformers.*"]
ignore_missing_imports = true

