ConvCourtName:
  type: list
  items:
    type: string
  description: "Name(s) of the court where the defendant was convicted or pleaded guilty."
  example: ["Crown Court at Southwark", "Magistrates Court of Liverpool", "Central Criminal Court"]

ConvictPleaDate:
  type: list
  items:
    type: string
  description: "Date(s) on which the defendant was convicted or pleaded guilty"
  example: ["2003-01-22", "2002-05-21", "2004-12-01"]

ConvictOffence:
  type: list
  items:
    type: string
  description: "Offence(s) of which the defendant was convicted"
  example: ["Dangerous driving (death by)", "Aggravated burglary", "Supply of controlled drugs (including conspiracy to)", "Manslaughter", "Pervert the course of justice", "Intent to endanger life"]

AcquitOffence:
  type: list
  items:
    type: string
  description: "Offence(s) of which the defendant was acquitted"
  example: ["Theft", "Money laundering", "Criminal damage", "Perjury"]

ConfessPleadGuilty:
  type: list
  items:
    type: string
  description: "Did the defendant confess or plead guilty?"
  example: ["pleaded guilty on 3rd April 2002", "pleaded not guilty", "No, denied offence", "Yes-Appellant1", "Yes", "No"]

PleaPoint:
  type: list
  items:
    type: string
  description: "Stage at which the plea was entered"
  example: ["in police presence", "at first court appearance", "on day of trial", "on re-arraignment", "earliest opportunity"]

RemandDecision:
  type: list
  items:
    type: string
  description: "Remand decision post-conviction"
  example: ["remanded on unconditional bail", "bail with curfew", "detained", "no", "Unconditional Bail", "Conditional Bail", "Remanded into custody", ]

RemandCustodyTime:
  type: list
  items:
    type: string
  description: "Duration of any remand in custody"
  example: ["38 days that he had spent on remand", "3 months", "30 days"]

SentCourtName:
  type: list
  items:
    type: string
  description: "Name(s) of the court where the defendant was sentenced."
  example: ["Crown Court at Canterbury", "Newcastle Crown Court", "Southend Crown Court"]

Sentence:
  type: list
  items:
    type: string
  description: "Sentence(s) imposed"
  example: ["2 years imprisonment", "£500 fine", "5 years custody"]

SentServe:
  type: list
  items:
    type: string
  description: "How sentences run"
  example: ["served concurrently", "consecutive", "Combination"]

WhatAncillary:
  type: list
  items:
    type: string
  description: "Ancillary orders applied by the court"
  example: ["Restraining order", "Compensation order", "Confiscation order", "Financial reporting order"]

OffSex:
  type: list
  items:
    type: string
  description: "Gender(s) of the defendant(s)"
  example: ["male", "female", "male and female", "All Male", "Mixed"]

OffAgeOffence:
  type: list
  items:
    type: string
  description: "Age of defendant at offence"
  example: ["21 years old", "age of 34", "28-42", "20s or 30s", "between thirty two and 35", "aged between 11 or 12 and 14 or 15 years old"]

OffJobOffence:
  type: list
  items:
    type: string
  description: "Employment status at offence"
  example: ["self-employed", "Student", "unemployed", "self-employed gardener", "Employed", "Unemployed", "Student", "junior manager"]

OffHomeOffence:
  type: list
  items:
    type: string
  description: "Accommodation status at offence"
  example: ["Fixed addresses", "hostel where he had been living", "appellant was homeless", "Temporary/not fixed", "Fixed Address", "Temporary Accommodation"]

OffMentalOffence:
  type: list
  items:
    type: string
  description: "Learning/developmental or mental-health issues noted"
  example: ["Mental health problems/difficulties", "learning disabilities", "Developmental /learning", "depression", "Had mental health problems", "Has learning difficulties", "mental health problems being severe reactive depression, requiring treatment"]

OffIntoxOffence:
  type: list
  items:
    type: string
  description: "Intoxication status"
  example: ["drunk and violent", "had taken heroin", "drink and drugs", "intoxicated with drugs and alcohol", "Yes-drinking&drugs", "Yes-drugs"]

OffVicRelation:
  type: list
  items:
    type: string
  description: "Relationship defendant→victim"
  example: ["Stranger", "Spouse", "ex-partner", "Related & Acquainted", "Relative", "Acquaintance"]

VictimType:
  type: list
  items:
    type: string
  description: "Type of victim"
  example: ["shop", "council", "individual person", "Individual person", "Government"]

VicNum:
  type: list
  items:
    type: string
  description: "Number of victims or ratio"
  example: ["1 of 3", "two of 36", "1-3 of 4", "2"]

VicSex:
  type: list
  items:
    type: string
  description: "Gender(s) of victim(s)"
  example: ["female", "both male and female", "Mixed", "All Male"]

VicAgeOffence:
  type: list
  items:
    type: string
  description: "Age of victim(s) at offence"
  example: ["30 years of age", "41 or 42", "40-42", "11-12 and 14-15"]

VicJobOffence:
  type: list
  items:
    type: string
  description: "Employment status of victim(s)"
  example: ["unemployed", "Student", "Employed", "Retired", "self-employed"]

VicHomeOffence:
  type: list
  items:
    type: string
  description: "Accommodation status of victim(s)"
  example: ["homeless",  "Fixed Address", "Temporary accommodation", "Sectioned"]

VicMentalOffence:
  type: list
  items:
    type: string
  description: "Learning/developmental or mental-health issues for victim(s)"
  example: ["mental health issues and learning disability", "Autism", "Had mental health problems", "Other"]

VicIntoxOffence:
  type: list
  items:
    type: string
  description: "Victim’s intoxication status"
  example: ["drunk", "cocaine use", "Yes-drugs", "Yes-drinking", "Yes-drinking&drugs", "No"]

ProsEvidTypeTrial:
  type: list
  items:
    type: string
  description: "Evidence types by prosecution"
  example: ["CCTV", "DNA match", "Victim testimony", "Expert report/testimony"]

DefEvidTypeTrial:
  type: list
  items:
    type: string
  description: "Evidence types by defence"
  example: ["Offender denies offence", "No DNA evidence", "Alibi claim"]

PreSentReport:
  type: list
  items:
    type: string
  description: "Risk level from pre-sentence report"
  example: ["high risk of reoffending", "low risk of the appellant re-offending, but a medium risk of harm to the public.", "medium risk of harm", "High risk of reoffending", "Medium risk of harm"]

AggFactSent:
  type: list
  items:
    type: string
  description: "Aggravating factors at sentencing"
  example: ["offence committed while on bail", "use of a weapon to frighten or injure victim"]

MitFactSent:
  type: list
  items:
    type: string
  description: "Mitigating factors at sentencing"
  example: ["offender showed genuine remorse", "Offender has no relevant previous convictions"]

VicImpactStatement:
  type: list
  items:
    type: string
  description: "Was a victim impact statement provided?"
  example: ["victim impact statement", "No", "Yes"]

Appellant:
  type: list
  items:
    type: string
  description: "Who brings the appeal"
  example: ["offender", "solicitor general", "Offenders"]

CoDefAccNum:
  type: list
  items:
    type: string
  description: "Number of co-defendants/co-accused"
  example: ["1", "two", "2"]

AppealAgainst:
  type: list
  items:
    type: string
  description: "Ground(s) for appeal"
  example: ["Conviction is unsafe", "Sentence is unduly lenient", "Conviction unsafe", "appeal against sentence"]

AppealGround:
  type: list
  items:
    type: string
  description: "Specific legal grounds of appeal"
  example: ["jury exposed to prejudicial evidence", "trial judge misdirected jury", "excessive sentence", "co-def received 33% credit/reduction in sentence, appellant received only 25%"]

SentGuideWhich:
  type: list
  items:
    type: string
  description: "Sentencing guidelines or statutes cited such as  s./section __ of (the) __ Act __ or [Sentencing Council’s (definitive) Guideline/s on/for… /Totality (principle/ of)…"
  example: ["section 25(1)(a) of the Identity Cards Act 2006", "section 155 of the Powers of Criminal Courts (Sentencing) Act 2000,", "section 52 of the Firearms Act 1968.", "section 18 of the Offences Against the Person Act 1861;", "section 114 of the Criminal Justice Act 2003", "Criminal Justice Act 1991"]

AppealOutcome:
  type: list
  items:
    type: string
  description: "Outcome of the appeal"
  example: ["Dismissed", "Allowed & Conviction Quashed", "Dismissed-Failed", "Appeal allowed and sentence reduced by 106 days", "Allowed and sentence replaced by less excessive sentence", "allowed and sentence replaced by more excessive sentence", "Allowed, sentence remains unchanged but will run from date of conviction", "The appeal accordingly fails and is dismissed.", "Allowed and sentence replaced with more lenient sentence", "Allowed and conviction quashed", "allowed - and sentence replaced by more lenient sentence", "both appeals against conviction & sentence are dismissed", "allowed and sentence replaced with more lenient sentence", "allowed", "We refuse leave", "allowed and convictions quashed, retrial ordered", "Appeal allowed and sentence replaced by more lenient sentence", "refuse"]

ReasonQuashConv:
  type: list
  items:
    type: string
  description: "Reasons for quashing conviction"
  example: ["The confiscation orders could not be upheld", "indictment charged the appellant in an impermissible manner", "procedural irregularity", "jury misdirection"]

ReasonSentExcessNotLenient:
  type: list
  items:
    type: string
  description: "Reasons why sentence was unduly excessive."
  example: ["lack of consideration for personal mitigation", "Mitigating factors should have been considered, such as young age of offenders", "seriousness of offence is too high", "excessive sentence when compared to co-offenders", "excessive sentence as mitigating factors not considered", "judge had erred in concluding that the appellant had a significant role", "judge did not account for mitigating factors correctly when sentencing", "judge fell into error when assessing the culpability of the offender"]

ReasonSentLenientNotExcess:
  type: list
  items:
    type: string
  description: "Reasons why sentence was unduly lenient."
  example: ["judge did not refer to relevant guideline", "Offence difficult to sentence as it happened in the past when offender was a child"]

ReasonDismiss:
  type: list
  items:
    type: string
  description: "Reasons for dismissal of the appeal"
  example: ["original sentence fell within guideline range", "no ground for appeal", judge made correct ruling", "no prejudice caused to offender", "judge categorised offence correctly"]
