ConvCourtName:
  type: list
  items:
    type: string
  description: "Name(s) of the court where the defendant was convicted or pleaded guilty."
  example: ["Crown Court at Southwark"]

ConvictPleaDate:
  type: list
  items:
      type: date
      format: ISO 8601
  description: "Date(s) on which the defendant was convicted or pleaded guilty"
  example: ["2003-01-22"]

ConvictOffence:
  type: list
  items:
    type: string
  description: "Offence(s) of which the defendant was convicted"
  example: ["Dangerous driving (death by)", "Aggravated burglary", "Supply of controlled drugs (including conspiracy to)", "Manslaughter", "Pervert the course of justice", "Intent to endanger life"]

AcquitOffence:
  type: list
  items:
    type: string
  description: "Offence(s) of which the defendant was acquitted"
  example: ["Theft", "Money laundering", "Criminal damage", "Perjury"]

ConfessPleadGuilty:
  type: list
  items:
    type: enum
    choices: ["Yes", "No"]
  description: "Did the defendant confess or plead guilty?"
  example: ["Yes"]

PleaPoint:
  type: list
  items:
    type: string
  description: "Stage at which the plea was entered"
  example: ["in police presence", "at first court appearance", "on day of trial", "on re-arraignment", "earliest opportunity"]

RemandDecision:
  type: list
  items:
    type: enum
    choices: ["Remanded into custody", "Unconditional Bail", "Conditional Bail", "No"]
  description: "Remand decision post-conviction"
  example: ["Unconditional Bail"]

RemandCustodyTime:
  type: list
  items:
    type: int
  description: "Duration in days of any remand in custody"
  example: ["4"]

SentCourtName:
  type: list
  items:
    type: string
  description: "Name(s) of the court where the defendant was sentenced."
  example: ["Crown Court at Canterbury", "Newcastle Crown Court", "Southend Crown Court"]

Sentence:
  type: list
  items:
    type: string
  description: "Sentence(s) imposed"
  example: ["2 years imprisonment", "£500 fine"]

SentServe:
  type: list
  items:
    type: enum
    choices: ["Concurrent", "Concurrently", "Combination", "Consecutive", "Consecutively", "Single"]
  description: "How sentences run"
  example: ["Concurrent"]

WhatAncillary:
  type: list
  items:
    type: string
  description: "Ancillary orders applied by the court"
  example: ["Restraining order", "Compensation order"]

OffSex:
  type: list
  items:
    type: enum
    choices: ["All Female", "All Male", "Mixed"]
  description: "Gender(s) of the defendant(s)"
  example: ["All Female"]

OffAgeOffence:
  type: list
  items:
    type: int
  description: "Age of defendant at offence"
  example: ["21", "34"]

OffJobOffence:
  type: list
  items:
    type: enum
    choices: ["Employed", "Unemployed", "Student", "Child", "Retired", "Other"]
  description: "Employment status at offence"
  example: ["Employed"]

OffHomeOffence:
  type: list
  items:
    type: enum
    choices: ["Fixed Address", "Temporary Accommodation", "Homeless", "Sectioned"]
  description: "Accommodation status at offence"
  example: ["Fixed Address"]

OffMentalOffence:
  type: list
  items:
    type: enum
    choices: ["Had mental health problems", "Learning/developmental", "Has learning difficulties", "Other"]
  description: "Learning/developmental or mental-health issues noted"
  example: ["Had mental health problems"]

OffIntoxOffence:
  type: list
  items:
    type: enum
    choices: ["Yes-drinking", "Yes-drinking&drugs", "Yes-drugs", "No"]
  description: "Intoxication status"
  example: ["Yes-drugs"]

OffVicRelation:
  type: list
  items:
    type: enum
    choices: ["Acquaintance", "Stranger", "Relative"]
  description: "Relationship defendant→victim"
  example: ["Acquaintance"]

VictimType:
  type: list
  items:
    type: enum
    choices: ["Individual person", "Individuals", "Company", "Organisation"]
  description: "Type of victim"
  example: ["Individual person"]

VicNum:
  type: list
  items:
    type: string
  description: "Number of victims or ratio"
  example: ["two of 36"]

VicSex:
  type: list
  items:
    type: enum
    choices: ["All Female", "All Male", "Mixed"]
  description: "Gender(s) of victim(s)"
  example: ["All Female"]

VicAgeOffence:
  type: list
  items:
    type: int
  description: "Age of victim(s) at offence"
  example: ["31"]

VicJobOffence:
  type: list
  items:
    type: enum
    choices: ["Employed", "Unemployed", "Student", "Retired", "Child", "Other"]
  description: "Employment status of victim(s)"
  example: ["Employed"]

VicHomeOffence:
  type: list
  items:
    type: enum
    choices: ["Homeless", "Fixed Address", "Temporary Accommodation", "Sectioned"]
  description: "Accommodation status of victim(s)"
  example: ["Homeless"]

VicMentalOffence:
  type: list
  items:
    type: enum
    choices: ["Had mental health problems", "Learning/developmental", "Has learning difficulties", "Other"]
  description: "Learning/developmental or mental-health issues for victim(s)"
  example: ["Had mental health problems"]

VicIntoxOffence:
  type: list
  items:
    type: enum
    choices: ["Yes-drinking", "Yes-drinking&drugs", "Yes-drugs", "No"]
  description: "Victim’s intoxication status"
  example: ["Yes-drugs"]

ProsEvidTypeTrial:
  type: list
  items:
    type: string
  description: "Evidence types by prosecution"
  example: ["CCTV", "DNA match", "Victim testimony", "Expert report/testimony"]

DefEvidTypeTrial:
  type: list
  items:
    type: string
  description: "Evidence types by defence"
  example: ["Offender denies offence", "No DNA evidence", "Alibi claim"]

PreSentReport:
  type: list
  items:
    type: enum
    choices: ["High risk of harm", "Low risk of reoffending", "High risk of reoffending", "Medium risk of reoffending", "Medium risk of harm", "Low risk of harm"]
  description: "Risk level from pre-sentence report"
  example: ["High risk of harm"]

AggFactSent:
  type: list
  items:
    type: string
  description: "Aggravating factors at sentencing"
  example: ["offence committed while on bail", "use of a weapon to frighten or injure victim"]

MitFactSent:
  type: list
  items:
    type: string
  description: "Mitigating factors at sentencing"
  example: ["offender showed genuine remorse", "Offender has no relevant previous convictions"]

VicImpactStatement:
  type: list
  items:
    type: enum
    choices: ["Yes", "No"]
  description: "Was a victim impact statement provided?"
  example: ["Yes"]

Appellant:
  type: list
  items:
    type: enum
    choices: ["Offender", "Attorney General", "Appellant", "Other"]
  description: "Who brings the appeal"
  example: ["Offender"]

CoDefAccNum:
  type: list
  items:
    type: int
  description: "Number of co-defendants/co-accused"
  example: ["2"]

AppealAgainst:
  type: list
  items:
    type: string
  description: "Ground(s) for appeal"
  example: ["Conviction is unsafe", "Sentence is unduly lenient", "Conviction unsafe", "appeal against sentence"]

AppealGround:
  type: list
  items:
    type: string
  description: "Specific legal grounds of appeal"
  example: ["jury exposed to prejudicial evidence", "trial judge misdirected jury", "excessive sentence", "co-def received 33% credit/reduction in sentence, appellant received only 25%"]

SentGuideWhich:
  type: list
  items:
    type: string
  description: "Sentencing guidelines or statutes cited such as  s./section __ of (the) __ Act __ or [Sentencing Council’s (definitive) Guideline/s on/for… /Totality (principle/ of)…"
  example: ["section 25(1)(a) of the Identity Cards Act 2006", "section 155 of the Powers of Criminal Courts (Sentencing) Act 2000,", "section 52 of the Firearms Act 1968.", "section 18 of the Offences Against the Person Act 1861;", "section 114 of the Criminal Justice Act 2003", "Criminal Justice Act 1991"]

AppealOutcome:
  type: list
  items:
    type: string
  description: "Outcome of the appeal"
  example: ["Dismissed", "Allowed & Conviction Quashed", "Dismissed-Failed", "Appeal allowed and sentence reduced by 106 days", "Allowed and sentence replaced by less excessive sentence", "allowed and sentence replaced by more excessive sentence", "Allowed, sentence remains unchanged but will run from date of conviction", "The appeal accordingly fails and is dismissed.", "Allowed and sentence replaced with more lenient sentence", "Allowed and conviction quashed", "allowed - and sentence replaced by more lenient sentence", "both appeals against conviction & sentence are dismissed", "allowed and sentence replaced with more lenient sentence", "allowed", "We refuse leave", "allowed and convictions quashed, retrial ordered", "Appeal allowed and sentence replaced by more lenient sentence", "refuse"]

ReasonQuashConv:
  type: list
  items:
    type: string
  description: "Reasons for quashing conviction"
  example: ["The confiscation orders could not be upheld", "indictment charged the appellant in an impermissible manner", "procedural irregularity", "jury misdirection"]

ReasonSentExcessNotLenient:
  type: list
  items:
    type: string
  description: "Reasons why sentence was unduly excessive."
  example: ["lack of consideration for personal mitigation", "Mitigating factors should have been considered, such as young age of offenders", "seriousness of offence is too high", "excessive sentence when compared to co-offenders", "excessive sentence as mitigating factors not considered", "judge had erred in concluding that the appellant had a significant role", "judge did not account for mitigating factors correctly when sentencing", "judge fell into error when assessing the culpability of the offender"]

ReasonSentLenientNotExcess:
  type: list
  items:
    type: string
  description: "Reasons why sentence was unduly lenient."
  example: ["judge did not refer to relevant guideline", "Offence difficult to sentence as it happened in the past when offender was a child"]

ReasonDismiss:
  type: list
  items:
    type: string
  description: "Reasons for dismissal of the appeal"
  example: ["original sentence fell within guideline range", "no ground for appeal", judge made correct ruling", "no prejudice caused to offender", "judge categorised offence correctly"]
