services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - nsa_dbdata:/data/db

  multiple-tor:
    build:
      context: ./multiple-tor
      args:
        SOCKET_START_PORT: 9000
        SOCKET_END_PORT: 9100
        CONTROL_START_PORT: 9900
        CONTROL_END_PORT: 10000
      dockerfile: ./Dockerfile
    ports:
      - 9000-9100:9000-9100
      - 9900-10000:9900-10000
    command: >
        python3 main.py --num-tors 50


volumes:
  nsa_dbdata:
  multitor_data:


