services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - nsa_dbdata:/data/db

  scraper:
    build:
        context: ../..
        dockerfile: docker/nsa/scraper/Dockerfile
    command: python scripts/dataset/nsa/run_scraper.py --mongo-db-uri mongodb://mongodb:27017
    tty: true
    depends_on:
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1h
        max_attempts: 10
        window: 120s

volumes:
  nsa_dbdata:
