name: meta-llama/Llama-3.1-8B-Instruct
tokenizer_name: ${.name}
adapter_path: data/experiments/fine-tune/llama_3.1_8b_instruct/en-appealcourt-coded-instruct/checkpoint-4
max_seq_length: 32_000
batch_size: 1
padding: longest
use_4bit: false
use_unsloth: false
