name: meta-llama/Llama-3.2-3B-Instruct
tokenizer_name: ${.name}
adapter_path: data/experiments/fine-tune/llama_3.2_3b_instruct/pl-court-frankowe-instruct/checkpoint-165
max_seq_length: 32_000
batch_size: 1
padding: longest
use_4bit: false
use_unsloth: false
