_org_name: meta-llama
_model_name: Meta-Llama-3-8B-Instruct
model_name: ${._org_name}/${._model_name}
tokenizer_name: ${._org_name}/${._model_name}

adapter_path: null

max_seq_length: 7_900
batch_size: 1
padding: longest
