name: unsloth/llama-3-8b-Instruct-bnb-4bit
tokenizer_name: ${.name}

adapter_path: data/experiments/fine-tune/Unsloth-Llama-3-8B-Instruct/pl-court-instruct/checkpoint-1500

max_seq_length: 7_900
batch_size: 8
padding: longest

use_unsloth: true
