name: unsloth/mistral-7b-instruct-v0.3-bnb-4bit
tokenizer_name: ${.name}

adapter_path: data/experiments/fine-tune/Unsloth-Mistral-7B-Instruct-v0.3/pl-court-instruct/checkpoint-1500

max_seq_length: 20_000
padding: longest
batch_size: 4

use_unsloth: true
