defaults:
  - model: Mistral-7B-Instruct-v0.2
  - dataset: pl-court-instruct
  - _self_

device: null
device_map: 'auto'
output_file: data/experiments/predict/${dataset._dataset_name}/${model._model_name}

max_new_tokens: 250

truncate_context: True
num_proc: 20
