defaults:
  - model: mistral
  - dataset: pl-court-instruct
  - _self_

output_dir: data/experiments/fine-tune/${model._model_name}/${dataset._dataset_name}
run_name: ${model._model_name}_${dataset._dataset_name}_fine_tune