defaults:
  - embedding_model: ???
  - dataset: pl-court-raw
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

length_adjust_mode: chunk
chunk_config:
  chunk_size: ${embedding_model.max_seq_length}
  min_split_chars: 10
  take_n_first_chunks: 16
batch_size: 64

output_dir: data/embeddings/${dataset.name}/${hydra:runtime.choices.embedding_model}/all_embeddings

hydra:
  output_subdir: null
  run:
    dir: .
