defaults:
  - embedding_model: qwen3-embedding-0.6b
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset_name: ???
chunk_config:
  chunk_size: 2048
  min_split_chars: 200
  take_n_first_chunks: 8
  chunk_overlap: 256

batch_size: 4096
num_output_shards: 10
ingest_batch_size: 32  # Batch size for ingestion
upsert: false  # Whether to update existing documents

output_dir: null

hydra:
  output_subdir: null
  run:
    dir: .

default_column_values:
  country: "Poland"
  language: "pl"
  document_type: "judgment"
