defaults:
  - embedding_model: mmlw-roberta-large
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

dataset_name: ???
chunk_config:
  chunk_size: ${embedding_model.max_seq_length}
  min_split_chars: 50
  take_n_first_chunks: 16
  chunk_overlap: 128

batch_size: 4096
num_output_shards: 10
ingest_batch_size: 32  # Batch size for ingestion
upsert: false  # Whether to update existing documents
max_documents: null  # Maximum number of documents to ingest (null for all)

output_dir: null

hydra:
  output_subdir: null
  run:
    dir: .

default_column_values:
  country: "Poland"
  language: "pl"
  document_type: "judgment"
