defaults:
  - model: Mistral-7B-Instruct-v0.2
  - dataset: pl-court-instruct
  - _self_

output_dir: data/experiments/fine-tune/${model._model_name}/${dataset._dataset_name}
run_name: ${model._model_name}_${dataset._dataset_name}_fine_tune

wandb_entity: graph-ml-lab-wust
wandb_project: juddges-fine-tune

truncate_context: True
num_proc: 20

hydra:  
  output_subdir: null  
  run:  
    dir: .
