defaults:
  - model: ../api_model/gpt_4.1
  - prompt: preannotate_label_studio_pl
  - _self_

ls_base_url: ${oc.env:LABEL_STUDIO_BASE_URL}
ls_api_key: ${oc.env:LABEL_STUDIO_API_KEY}
project_name: "Juddges Project: Swiss Frank"
text_field: "text"
model_version: ${model.name}

annotation_schema: label_studio_toolkit.schemas.swiss_frank.SwissFrancJudgmentAnnotation 

model:
  request_cache_db: .langchain_annotation_cache.db
