defaults:
  - model: ???
  - dataset: ???
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model:
  batch_size: 4

device_map: 'auto'
output_file: data/experiments/predict/${hydra:runtime.choices.dataset}/${hydra:runtime.choices.model}/outputs_${random_seed}.json
truncate_context: True
generate_kwargs:
  max_new_tokens: ${dataset.max_output_tokens}
  do_sample: true
  temperature: 0.1

random_seed: ???

hydra:
  output_subdir: null
  run:
    dir: .
