defaults:
  - model: ???
  - dataset: pl-court-instruct
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device_map: 'auto'
output_file: ???
truncate_context: True
generate_kwargs:
  max_new_tokens: ${dataset.max_output_tokens}
  do_sample: true
  temperature: 0.1

random_seed: ???

hydra:
  output_subdir: null
  run:
    dir: .
