defaults:
  - dataset: pl-court-instruct
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

model_version: ???
max_seq_len: 8_000
temperature: 0.1
seed: ???
batch_size: 32
output_file: ???
request_cache_db: .langchain_cache.db

hydra:
  output_subdir: null
  run:
    dir: .
