defaults:
  - model: ???
  - dataset: pl-court-instruct
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

device_map: 'auto'
output_file: data/experiments/predict/${hydra:runtime.choices.dataset}/outputs_${hydra:runtime.choices.model}.json
metrics_file: data/experiments/predict/${hydra:runtime.choices.dataset}/metrics_${hydra:runtime.choices.model}.json

truncate_context: True
generate_kwargs:
  max_new_tokens: 250
  do_sample: False

hydra:
  output_subdir: null
  run:
    dir: .
