defaults:
  - model: ???
  - dataset: pl-court-instruct
  - _self_

device_map: 'auto'
output_file: data/experiments/predict/${dataset.name}/outputs_${hydra:runtime.choices.model}.json
metrics_file: data/experiments/predict/${dataset.name}/metrics_${hydra:runtime.choices.model}.json

max_new_tokens: 250
truncate_context: True

hydra:  
  output_subdir: null  
  run:  
    dir: .
