# Universal embedding and ingestion configuration
# This configuration works with any HuggingFace dataset

# Dataset configuration
dataset_name: "juddges/pl-court-raw"  # Can be overridden via command line

# Embedding model configuration
embedding_model:
  name: "sdadas/mmlw-roberta-large"
  max_seq_length: 512

# Output configuration
output_dir: "data/embeddings/${dataset_name}/${embedding_model.name}"
num_output_shards: 4

# Processing configuration
batch_size: 16
max_documents: null  # null means process all documents
num_proc: 4

# Ingestion configuration
ingest_batch_size: 32
upsert: true
skip_validation: false
preview_only: false
force: false

# Chunking configuration (for text splitting)
chunk_config:
  chunk_size: 1000
  chunk_overlap: 200
  chunk_strategy: "recursive"  # or "semantic", "fixed"

# Default values to add to documents if missing
default_column_values:
  document_type: "judgment"
  ingestion_date: "2024-01-01T00:00:00Z"

# Advanced options
processing_options:
  parallel_processing: true
  memory_efficient: true
  error_recovery: true
  progress_tracking: true

# Validation options
validation:
  sample_size: 1000
  strict_mode: false
  check_duplicates: true
  validate_dates: true
  validate_text_quality: true

# Weaviate connection (uses environment variables)
weaviate:
  host: "${oc.env:WEAVIATE_HOST,localhost}"
  port: "${oc.env:WEAVIATE_PORT,8080}"
  grpc_port: "${oc.env:WEAVIATE_GRPC_PORT,50051}"
  api_key: "${oc.env:WEAVIATE_API_KEY,}"

# Logging configuration
logging:
  level: "INFO"
  format: "{time} | {level} | {message}"
  file_output: "logs/universal_ingestion.log"