# Autogenerated by nbdev

d = {
    "settings": {
        "branch": "master",
        "doc_baseurl": "/juddges",
        "doc_host": "https://laugustyniak.github.io",
        "git_url": "https://github.com/laugustyniak/juddges",
        "lib_path": "juddges",
    },
    "syms": {},
}
