# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/juddges',
                'doc_host': 'https://laugustyniak.github.io',
                'git_url': 'https://github.com/laugustyniak/juddges',
                'lib_path': 'juddges'},
  'syms': { 'juddges.data.models': {},
            'juddges.data.pl_court_api': {},
            'juddges.preprocessing.parser_base': {},
            'juddges.preprocessing.pl_court_parser': {},
            'juddges.prompts.information_extraction': {},
            'juddges.settings': {}}}
