from enum import Enum


class Judgment(Enum):
    ID = "_id"
    SIGNATURE = "signature"
    DATE = "date"
    PUBLICATION_DATE = "publicationDate"
    LAST_UPDATE = "lastUpdate"
    COURT_ID = "courtId"
    DEPARTMENT_ID = "departmentId"
    TYPE = "type"
    EXCERPT = "excerpt"
    CONTENT = "content"
    CHAIRMAN = "chairman"
    DECISION = "decision"
    JUDGES = "judges"
    LEGAL_BASES = "legalBases"
    PUBLISHER = "publisher"
    RECORDER = "recorder"
    REFERENCES = "references"
    REVISER = "reviser"
    THEME_PHRASES = "themePhrases"
    NUM_PAGES = "num_pages"
    TEXT = "text"
    VOL_NUMBER = "vol_number"
    VOL_TYPE = "vol_type"
    COURT_NAME = "court_name"
    DEPARTMENT_NAME = "department_name"
    TEXT_LEGAL_BASES = "text_legal_bases"
    EMBEDDING = "embedding"
