name: python-check
on: [ pull_request, push ]

jobs:
  python-check:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os:
          - ubuntu-latest
#          - macos-latest # at the moment bitsandbytes installation fails on macOS
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: make install
      - name: Check
        run: make check

  python-test:
    needs:
      - python-check
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os:
          - ubuntu-latest
#          - macos-latest # at the moment bitsandbytes installation fails on macOS
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: make install
      - name: Check
        run: make test
