name: python-lint-and-test
on: [ push ]

jobs:
  python-check:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os:
          - ubuntu-latest
#          - macos-latest # at the moment bitsandbytes installation fails on macOS
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install deps
        run: make install_cpu
      - name: Lint
        run: make check

  python-test:
    needs:
      - python-check
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.11 ]
        os:
          - ubuntu-latest
#          - macos-latest # at the moment bitsandbytes installation fails on macOS
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
      - name: Install deps
        run: make install_cpu
      - name: Test
        env:
          HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
        run: make test
